export default {
    "zh_CN": {
        'shareTitle': 'Hello，推荐您一个MFA小程序，我也在使用哦~ 👍',
        'singlePageTitle': '请前往小程序使用完整服务',
        'Back': '返回',
        'Authenticator': '身份验证器',
        'Account has been added': '账号已添加',
        'added—help': '当系统要求您输入验证码时，您可在此处获取。验证码每次都不相同，因此您无需记住它。',
        'add-account': '添加账号',
        'Rename': '重命名',
        'save': '保存',
        'cancel': '取消',
        'Whether to delete': '是否刪除',
        '?': '？',
        'Deleting the account will': '删除该帐号会',
        'cause you cannot': '导致您无法',
        'generate a verification code, but': '生成验证码，但',
        'will not': '不会',
        'nted': '关闭双重身份验证。您可能会因此无法登录自己的帐号。',
        'dtt': '在删除该帐号之前，请执行以下操作：',
        'dt1': '关闭该帐号的两双重身份验证功能，或者',
        'dt2': '确保您可以通过其他方法生成验证码。',
        'da': '删除账号',
        'error': '错误',
        'crq': '无法解读 QR 码',
        'OK': '确定',
        'sqc': '扫描二维码',
        'Enter-key': '输入提供的密钥',
        'edit': '修改',
        'delete': '删除',
        'check_info': '检查密钥值',
        'stt': '为您的 账号 开启两步验证后，您需要',
        'st1': '您的密码',
        'st2': '该应用将为您生成的验证码',
        'st3': '注意：请妥善保管您的 密钥信息 或 二维码（落叶🍂），建议将该小程序 添加到我的小程序 哦^_^',
        'start': '开始',
        'i-1': '为确保 ',
        'i-2': ' 的密钥值准确无误，请核对下列值是否与服务器提供的完整性校验值一致：',
    },
    "zh_HK": {
        'shareTitle': 'Hello，推薦您一個MFA小程序，我也在使用哦~ 👍',
        'singlePageTitle': '請前往小程序使用完整服務',
        'Back': '返回',
        'Authenticator': '身份驗證器',
        'Account has been added': '賬號已添加',
        'added—help': '當系統要求您輸入驗證碼時，您可在此處獲取。驗證碼每次都不相同，因此您無需記住它。',
        'add-account': '添加賬號',
        'Rename': '重命名',
        'save': '保存',
        'cancel': '取消',
        'Whether to delete': '是否刪除',
        '?': '？',
        'Deleting the account will': '刪除該帳號會',
        'cause you cannot': '導致您無法',
        'generate a verification code, but': '生成驗證碼，但',
        'will not': '不会',
        'nted': '關閉雙重身份驗證。您可能會因此無法登錄自己的帳號。',
        'dtt': '在刪除該帳號之前，請執行以下操作：',
        'dt1': '關閉該帳號的兩雙重身份驗證功能，或者',
        'dt2': '確保您可以通過其他方法生成驗證碼。',
        'da': '刪除賬號',
        'error': '錯誤',
        'crq': '無法解讀 QR 碼',
        'OK': '確定',
        'sqc': '掃描二維碼',
        'Enter-key': '輸入提供的密鑰',
        'edit': '修改',
        'delete': '删除',
        'check_info': '檢查密鑰值',
        'stt': '為您的 賬號 開啟兩步驗證後，您需要',
        'st1': '您的密碼',
        'st2': '該應用將為您生成的驗證碼',
        'st3': '注意：請妥善保管您的 密鑰信息 或 二維碼（落叶🍂），建議將該小程序 添加到我的小程序 哦^_^',
        'start': '開始',
        'i-1': '為確保 ',
        'i-2': ' 的密鑰值準確無誤，請核對下列值是否與服務器提供的完整性校驗值一致：',
    },
    "en": {
        'shareTitle': 'Hello, I recommend an MFA Mini Program, I am also using it~ 👍',
        'singlePageTitle': 'Please go to the Mini Program to use the full service',
        'Back': 'Back',
        'Authenticator': 'Authenticator',
        'Account has been added': 'Account has been added',
        'added—help': 'When the system asks you to enter the verification code, you can get it here. The verification code is different every time, so you don’t need to remember it.',
        'add-account': 'Add account',
        'Rename': 'Rename',
        'save': 'Save',
        'cancel': 'Cancel',
        'Whether to delete': 'Whether to delete',
        '?': '?',
        'Deleting the account will': 'Deleting the account will ',
        'cause you cannot': 'cause you cannot ',
        'generate a verification code, but': 'generate a verification code, but ',
        'will not': 'will not ',
        'nted': 'turn off two-factor authentication. You may be unable to log in to your account as a result.',
        'dtt': 'Before deleting the account, please do the following:',
        'dt1': 'Turn off the two-factor authentication for this account, or',
        'dt2': 'make sure you can generate verification codes by other methods.',
        'da': 'Delete account',
        'error': 'Error',
        'crq': 'Can\'t read QR code',
        'OK': 'OK',
        'sqc': 'Scan QR code',
        'Enter-key': 'Enter the provided key',
        'edit': 'Edit',
        'delete': 'Delete',
        'check_info': 'Check the key value',
        'stt': 'After turning on two-step verification for your account, you need to',
        'st1': 'Your password',
        'st2': 'The verification code that the app will generate for you',
        'st3': 'Note: Please keep your key information or QR code (落叶🍂) properly. It is recommended to add this Mini Program to my Mini Program ^_^',
        'start': 'Start',
        'i-1': 'To ensure that the key value of ',
        'i-2': ' is accurate, please check whether the following values are consistent with the integrity check values provided by the server:',
    },
};