export default {
    "zh_CN": {
        'shareTitle': 'Hello，推荐您一个MFA小程序，我也在使用哦~ 👍',
        'Back': '返回',
        'bat': '基于时间',
        'batc': '基于计数器',
        'ks': '密钥值太短',
        'ke': '密钥值中含有非法字符',
        'it': '输入账号详情',
        'ih': '输入账户名称',
        'ik': '输入你的密钥',
        'add': '添加',
        'nt': '请妥善保管您的密钥信息，以防止您误删数据后影响使用，建议将该小程序 添加到我的小程序 哦^_^，有问题请通过设置面板页面【联系客服】',
    },
    "zh_HK": {
        'shareTitle': 'Hello，推薦您一個MFA小程序，我也在使用哦~ 👍',
        'Back': '返回',
        'bat': '基於時間',
        'batc': '基於計數器',
        'ks': '密鑰值太短',
        'ke': '密鑰值中含有非法字符',
        'it': '輸入賬號詳情',
        'ih': '輸入賬戶名稱',
        'ik': '輸入你的密鑰',
        'add': '添加',
        'nt': '請妥善保管您的密鑰信息，以防止您誤刪數據後影響使用，建議將該小程序 添加到我的小程序 哦^_^，有問題請通過設置面板頁面【聯繫客服】',
    },
    "en": {
        'shareTitle': 'Hello, I recommend an MFA Mini Program, I am also using it~ 👍',
        'Back': 'Back',
        'bat': 'Based on time',
        'batc': 'Counter based',
        'ks': 'The key value is too short',
        'ke': 'The key value contains illegal characters',
        'it': 'Enter account details',
        'ih': 'Enter account name',
        'ik': 'Enter your key',
        'add': 'Add',
        'nt': 'Please keep your key information properly to prevent you from accidentally deleting the data and affecting the use. It is recommended to add this Mini Program to my Mini Program ^_^, if you have any questions, please contact customer service through the settings panel page',
    },
};